halt: false
environment_module: false
inputs:
  - name: env_name
    user_facing: false
    description: Opta Environment name
    default: None
  - name: layer_name
    user_facing: false
    description: Opta Layer name
    default: None
  - name: module_name
    user_facing: false
    description: Opta Module name
    default: None
outputs:
  - name: db_user
    export: false
    description: The database user
  - name: db_password
    export: false
    description: The database password
  - name: db_host
    export: false
    description: The database host
  - name: db_name
    export: false
    description: The database ip
output_providers: { }
output_data: { }